# Generated by Django 4.2.3 on 2023-07-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSapp', '0003_alter_studentform_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='materials_provide_1',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='materials_provide_2',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='materials_provide_3',
        ),
    ]
