# Generated by Django 4.2.3 on 2023-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSapp', '0006_rename_post_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
