# Generated by Django 4.2.3 on 2023-07-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_category_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
